const GENES = {
  'Pastel': { short: 'Pas', category: 'recessive', states: ['Normal', 'Heterozygous', 'Visual'] },
  'Ball': { short: 'Ball', category: 'recessive', states: ['Normal', 'Heterozygous', 'Visual'] },
  'Cinnamon': { short: 'Cinn', category: 'recessive', states: ['Normal', 'Heterozygous', 'Visual'] },
  'Butter': { short: 'But', category: 'recessive', states: ['Normal', 'Heterozygous', 'Visual'] },
  'Pinstripe': { short: 'Pin', category: 'dominant', states: ['Normal', 'Visual'] },
  'Yellowbelly': { short: 'YB', category: 'recessive', states: ['Normal', 'Heterozygous', 'Visual'] },
  'Mojave': { short: 'Moj', category: 'recessive', states: ['Normal', 'Heterozygous', 'Visual'] },
  'Lemon Blast': { short: 'LB', category: 'dominant', states: ['Normal', 'Visual'] },
  'Enchi': { short: 'Enc', category: 'recessive', states: ['Normal', 'Heterozygous', 'Visual'] },
  'Scale': { short: 'Scl', category: 'recessive', states: ['Normal', 'Heterozygous', 'Visual'] },
  'Fire': { short: 'Fire', category: 'dominant', states: ['Normal', 'Visual'] },
  'OBE': { short: 'OBE', category: 'recessive', states: ['Normal', 'Heterozygous', 'Visual'] },
  'Spotnose': { short: 'SpN', category: 'recessive', states: ['Normal', 'Heterozygous', 'Visual'] },
  'Firefly': { short: 'FF', category: 'dominant', states: ['Normal', 'Visual'] },
  'Ghost': { short: 'Gho', category: 'recessive', states: ['Normal', 'Heterozygous', 'Visual'] },
  'Phantom': { short: 'Phe', category: 'recessive', states: ['Normal', 'Heterozygous', 'Visual'] },
  'Asphalt': { short: 'Asp', category: 'recessive', states: ['Normal', 'Heterozygous', 'Visual'] },
  'Mahogany': { short: 'Mah', category: 'recessive', states: ['Normal', 'Heterozygous', 'Visual'] },
  'Chrome': { short: 'Chr', category: 'recessive', states: ['Normal', 'Heterozygous', 'Visual'] },
  'Emerine': { short: 'Eme', category: 'recessive', states: ['Normal', 'Heterozygous', 'Visual'] },
  'Sable': { short: 'Sab', category: 'recessive', states: ['Normal', 'Heterozygous', 'Visual'] },
  'Sulfur': { short: 'Sul', category: 'recessive', states: ['Normal', 'Heterozygous', 'Visual'] },
  'Black': { short: 'Blk', category: 'recessive', states: ['Normal', 'Heterozygous', 'Visual'] },
  'Desert Ghost': { short: 'DG', category: 'recessive', states: ['Normal', 'Heterozygous', 'Visual'] },
  'Granite': { short: 'Gra', category: 'recessive', states: ['Normal', 'Heterozygous', 'Visual'] },
  'Acid': { short: 'Aci', category: 'recessive', states: ['Normal', 'Heterozygous', 'Visual'] },
  'Ultramel': { short: 'UM', category: 'recessive', states: ['Normal', 'Heterozygous', 'Visual'] },
  'Champagne': { short: 'Cha', category: 'recessive', states: ['Normal', 'Heterozygous', 'Visual'] },
  'Caramel': { short: 'Car', category: 'recessive', states: ['Normal', 'Heterozygous', 'Visual'] },
  'Red Stripe': { short: 'RS', category: 'dominant', states: ['Normal', 'Visual'] },
  'Piebald': { short: 'Pib', category: 'recessive', states: ['Normal', 'Heterozygous', 'Visual'] },
  'Bamboo': { short: 'Bam', category: 'recessive', states: ['Normal', 'Heterozygous', 'Visual'] },
  'Striped': { short: 'Str', category: 'recessive', states: ['Normal', 'Heterozygous', 'Visual'] },
  'Woma': { short: 'Wom', category: 'recessive', states: ['Normal', 'Heterozygous', 'Visual'] },
  'Ruler': { short: 'Rul', category: 'recessive', states: ['Normal', 'Heterozygous', 'Visual'] },
  'Red Tail Boa': { short: 'RTB', category: 'recessive', states: ['Normal', 'Heterozygous', 'Visual'] },
  'Leatherback': { short: 'LB', category: 'incdominant', states: ['Normal', 'Visual', 'Super (Silkback)'] },
  'Witblits': { short: 'Wit', category: 'recessive', states: ['Normal', 'Heterozygous', 'Visual'] },
  'Zero': { short: 'Zero', category: 'recessive', states: ['Normal', 'Heterozygous', 'Visual'] },
  'Stripe': { short: 'Str', category: 'nonmendelian', states: ['None', 'Low Expression', 'High Expression', 'Unknown'] }
};

const SPECIAL_NOTES = {
  'Leatherback': 'Incomplete dominant. Homozygous = Silkback',
  'Witblits + Zero': 'Both Visual = Wero offspring',
  'Silkback × Silkback': 'Health concerns in offspring'
};
